replicaCount: 3

image:
  repository: ipfs/go-ipfs
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4001

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
