apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4001
      targetPort: 4001
      name: port4001
    - port: 5001
      targetPort: 5001
      name: port5001
    - port: 8080
      targetPort: 8080
      name: port8080
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
